name: CI workflow

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install -r requirements.txt
      - name: Lint with flake8
        run: |
          pip3 install flake8
          flake8 .

      - name: Run Tests
        run: |
          pip3 install pytest-cov
          pytest --cov=service tests/
